ApiManagement/WebApplication1/Controllers/ApiManage/ApiAccountController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.App_DLL;

namespace WebApplication1.Controllers.ApiManage
{
    public class ApiAccountController : Controller
    {
        // GET: Account
        public ActionResult Index()
        {
            return PartialView();
        }
        public string register() {
             DataBase db = new DataBase();
            try
            {
                string api_name = Request.Form["api_name"];
                string api_password = Request.Form["api_password"];
                string api_email = Request.Form["api_email"];
                string api_photo = Request.Form["api_photo"];
                Guid id = Guid.NewGuid();
                DateTime create_time = DateTime.Now;
                SqlParameter[] parameters = new SqlParameter[] {
                    new SqlParameter("@id", id),
                     new SqlParameter("@api_name", api_name),
                    new SqlParameter("@api_password", api_password),  
                    new SqlParameter("@api_photo", api_photo),
                    new SqlParameter("@api_email", api_email),
                     new SqlParameter("@create_time", create_time),
                };
                string cmdtex = "insert into Api_User (id,user_name,password,mobile,email,create_time) values(@id,@api_name,@api_password,@api_photo,@api_email,@create_time)";
                db.Select(cmdtex,parameters);
                db.Close();
                Session["user_name"] = api_name;
                return "true";
            }
            catch(Exception e){
                db.Close();
                return e.Message;
            }
        }

        public ActionResult Login()
        {
            return PartialView();
        }
        public string check() {
            string user_name = Request.Form["api_name"];
            string password = Request.Form["api_password"];
            DataBase db = new DataBase();
            DataTable dt = new DataTable();
            SqlParameter[] parameters = new SqlParameter[] {
                        new SqlParameter("@user_name", user_name),new SqlParameter("@password", password) };
            string cmdtex = "select id from Api_User where user_name=@user_name and password=@password";
            dt = db.Select(cmdtex,parameters);
            db.Close();
            if (dt.Rows.Count > 0)
            {
                Session["user_name"] = user_name;
                return "true";
            }
            else {
                return "false";

            }
        }

        public ActionResult logout() {

            Session.Abandon();

            return RedirectToAction("index", "Home");

        }
    }
}

ApiManagement/WebApplication1/Controllers/ApiManage/ApiManagementController.cs
using System;
using System.Data;
using System.Data.SqlClient;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using WebApplication1.App_DLL;
using WebApplication1.App_Fifter;
using WebApplication1.App_Handler;

namespace WebApplication1.Controllers.ApiManage
{
    [AccountFilter]
    public class ApiManagementController : Controller
    {
        // GET: ApiManagement
        public ActionResult Index(string id,string sid,int version)
        {
            ViewBag.sid = sid;
            ViewBag.id = id;
            ViewBag.version = version;
            ViewBag.user_name = Session["user_name"];
            return View();
        }
        public ActionResult History(string sid) {
            ViewBag.user_name = Session["user_name"];
            ViewBag.sid = sid;
            return View();
        }
        public string GetHistory(string sid) {         
            DataTable dt3 = new DataTable();
            DataBase db = new DataBase();
            SqlParameter[] parameters = new SqlParameter[] { new System.Data.SqlClient.SqlParameter("@sid", sid)};
            string cmdtex3 = "select id,sid,api_name,version,create_time,change_reason,user_name from Api_content where sid=@sid";//获取旧版本API列表
            
            dt3 = db.Select(cmdtex3,parameters);
            db.Close();
            return JSONHandler.Dtb2Json(dt3);
        }
        public ActionResult Add() {

            ViewBag.user_name = Session["user_name"];
            return View();
        }
        public string GetApiList() {
            DataTable dt = new DataTable();
            DataBase db = new DataBase();
            string cmdtex = "select b.id,b.sid,b.api_name,b.api_description,b.version  from (select sid,max(version) version from Api_content group by sid) as a,Api_content as b where a.sid=b.sid and a.version=b.version order by b.api_name";
            dt = db.GetRecords(cmdtex);
            db.Close();
            if (dt.Rows.Count > 0)
            {
                return JSONHandler.Dtb2Json(dt);
            }
            else {
                return null;
            }
        }
        public string GetApiList_Ajax(string apiname) {
            DataTable dt = new DataTable();
            DataBase db = new DataBase();
            string cmdtex = "select top 10 b.id,b.sid,b.api_name,b.api_description,b.version  from (select sid,max(version) version from Api_content group by sid) as a,Api_content as b where a.sid=b.sid and a.version=b.version  and b.api_name like '%"+apiname+"%'  order by b.api_name";
            dt = db.GetRecords(cmdtex);
            db.Close();
            if (dt.Rows.Count > 0)
            {
                return JSONHandler.Dtb2Json(dt);
            }
            else
            {
                return null;
            }
        }
        public string GetApiContent(string id,string sid) {
            DataTable dt1 = new DataTable();
            DataTable dt2 = new DataTable();             
            DataBase db = new DataBase();
            string result = "";
            SqlParameter[] parameters = new SqlParameter[] { new System.Data.SqlClient.SqlParameter("@id", id) };
            string cmdtex1 = "select * from Api_content where id=@id";//获取该版本（文档）的内容
            string cmdtex2 = "select * from Api_parameter where id=@id"; //获取该版本（文档）的参数内容                
            dt1 = db.Select(cmdtex1,parameters);
            dt2 = db.Select(cmdtex2,parameters);      
            result = "{\"main\":" + JSONHandler.Dtb2Json(dt1) + ",\"parameter\":" + JSONHandler.Dtb2Json(dt2) + "}";
            db.Close();
            return result;

        }
        public string AddContent()
        {
            if (Session["user_name"] != null)
            {
                string user_name = Session["user_name"].ToString();
                string result = "";
                JavaScriptSerializer jss = new JavaScriptSerializer();
                if (Request.Form["api_name"] != null)
                {
                    Guid id = Guid.NewGuid();
                    //判断是修改还是新增
                    long sid;
                    int version;
                    var change_reason="";
                    if (Request.Form["sid"] != null && Request.Form["version"] != null && Request.Form["sid"] != "" && Request.Form["version"] != "")
                    {
                        sid = Convert.ToInt64(Request.Form["sid"]);
                        version = Convert.ToInt32(Request.Form["version"]) + 1;
                       
                    }
                    else
                    {
                        
                        sid = TimerHandler.GetTimeStamp();
                        version = 0;
                    }
                    if (Request.Form["change_reason"] != null && Request.Form["change_reason"] != "")
                    {
                        change_reason = Request.Form["change_reason"];
                    }
                    else {
                        change_reason = "";
                    }
                    var api_name = Request.Form["api_name"];
                    var api_description = Request.Form["api_description"];
                    var api_introduction = Request.Form["api_introduction"];
                    var request_url = Request.Form["request_url"];
                    var request_method = Request.Form["request_method"];
                    var return_value_type = Request.Form["return_value_type"];
                    var request_sample = Request.Form["request_sample"];
                    var response_sample = Request.Form["response_sample"];
                    var unnormal_response_sample = Request.Form["unnormal_response_sample"];
                    var error_code_explanation = Request.Form["error_code_explanation"];
                    var remark = Request.Form["remark"];
                    var create_time = DateTime.Now;
                    var online_status = 3;//0计划中、1开发中、2已上线、3待下线、4已下线
                    var is_history = 0;//0不是历史记录、1是历史记录
                    var check_status = 0;//0待核验、1核验已通过、2核验未通过
                    var is_deleted = 0;//0未删除、1已删除
                    var request_parameter = jss.Deserialize(Request.Form["request_parameter"], typeof(string[][])) as string[][];
                    // List<Request_parameter> request_parameter = jss.Deserialize<List<Request_parameter>>(Request.Form["request_parameter"]);
                    var response_parameter = jss.Deserialize(Request.Form["response_parameter"], typeof(string[][])) as string[][];
                   
                    DataBase db = new DataBase();
                    db.Transaction();
                    try
                    {
                        SqlParameter[] parameters = new SqlParameter[] {
                        new SqlParameter("@id", id),
                        new SqlParameter("@sid", sid),
                        new SqlParameter("@api_name", api_name),
                        new SqlParameter("@api_description", api_description),
                        new SqlParameter("@api_introduction", api_introduction),
                        new SqlParameter("@request_url", request_url),
                        new SqlParameter("@request_method", request_method),
                        new SqlParameter("@return_value_type", return_value_type),
                        new SqlParameter("@request_sample", request_sample),
                        new SqlParameter("@response_sample", response_sample),
                        new SqlParameter("@unnormal_response_sample", unnormal_response_sample),
                        new SqlParameter("@error_code_explanation", error_code_explanation),
                        new SqlParameter("@remark", remark),
                        new SqlParameter("@version", version),
                        new SqlParameter("@create_time", create_time),
                        new SqlParameter("@online_status", online_status),
                        new SqlParameter("@is_history", is_history),
                        new SqlParameter("@check_status", check_status),
                        new SqlParameter("@is_deleted", is_deleted),
                        new SqlParameter("@change_reason", change_reason),
                        new SqlParameter("@user_name", user_name),
                        };
                        string cmdtex = "insert into Api_content (id,sid,api_name,api_description,api_introduction,request_url,request_method,return_value_type,request_sample,response_sample,unnormal_response_sample,error_code_explanation,remark,version,create_time,online_status,is_history,check_status,is_deleted,change_reason,user_name)";
                        cmdtex += " values(@id,@sid,@api_name,@api_description,@api_introduction,@request_url,@request_method,@return_value_type,@request_sample,@response_sample,@unnormal_response_sample,@error_code_explanation,@remark,@version,@create_time,@online_status,@is_history ,@check_status ,@is_deleted ,@change_reason,@user_name)";
                        string cmdtex2 = "";
                        if (request_parameter.Length > 0)
                        {
                            for (int i = 0; i <= request_parameter.Length - 1; i++)
                            {
                                Guid parameter_id = Guid.NewGuid();
                                SqlParameter[] parameters2 = new SqlParameter[] {
                                  new SqlParameter("@parameter_id", parameter_id),
                                  new SqlParameter("@id", id),
                                  new SqlParameter("@parameter_name", request_parameter[i][0]),
                                  new SqlParameter("@parameter_type", request_parameter[i][1]),
                                  new SqlParameter("@parameter_length", request_parameter[i][2]),
                                  new SqlParameter("@is_required", request_parameter[i][5]),

ApiManagement/WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>API管理</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

</head>
<body>
    <div style="padding:4px 10px 4px 10px;">
        <div class="">
            <div class="col-md-12 column">
                <nav class="navbar navbar-default" role="navigation">    
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">                    
                        <div class="navbar-form navbar-left" role="search">
                            <a href="@Url.Action("index", "Home")">主页</a>
                            <div class="form-group">
                                <input type="text" class="form-control" id="i_query"/>               
                            </div>                           
                            <button type="submit" class="btn btn-default">Query</button>    <button class="btn btn-default" onclick="window.open('@Url.Action("Add", "ApiManagement")')">Add</button>
                        </div>                     
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                               <a >@ViewBag.user_name</a>
                            </li>
                            <li >
                                <a href="@Url.Action("logout", "ApiAccount")" >退出</a>
                              
                            </li>
                        </ul>
                    </div>      
                    <div style="width:250px;max-height:300px;position:fixed;left:90px; overflow:auto;" id="apilist">               
                    </div>                 
                </nav>
            </div>
        </div>
        <div class="">
            <div class="col-md-2" style="OVERFLOW-Y: auto; OVERFLOW-X:hidden; height:1200px;">
             @Html.Partial("_Navigation")
            </div>
            <div class="col-md-10 column" style="OVERFLOW-Y: auto; OVERFLOW-X:hidden; height:1200px;">
                @RenderBody()
            </div>         
        </div>  
    </div>
    @RenderSection("scripts", required: false)
<script>
    var apilist = "";
    $(function () {
        $("#i_query").keyup(function () {
            $("#apilist").show(200);
           var apiname=$("#i_query").val();
            $.ajax({
                url: "@Url.Action("GetApiList_Ajax", "ApiManagement")", //请求的url地址http://localhost:7460/ApiManagement/GetApiList_Ajax?apiname=" + apiname + "
                dataType: "json", //返回格式为json
                async: true,//请求是否异步，默认为异步，这也是ajax重要特性
                data: { "apiname": apiname },   //参数值
                type: "get", //请求方式
                beforeSend: function () {
                    //请求前的处理
                },
                success: function (data) {           
                    if (data != null && data != "") {

                        var jsondata = eval(data);

                        $("#apilist").empty();
                        apilist = "<ul>";
                        $(data).each(function () {
                            apilist += " <li><a href='../ApiManagement/index?id=" + this["id"] + "&&sid=" + this["sid"] + "&&version=" + this["version"] + "'>" + this["api_name"] + "</a></li>";     //           
                        });
                        apilist += "</ul>";
                        $("#apilist").html(apilist);
                    }
                    
                },
                complete: function () {

                    //请求完成的处理
                },
                error: function (data) {
                    //console.log(data);
                    //请求出错处理
                }
            });

        });
        $("#apilist").mouseleave(function () {
            $("#apilist").empty();
            $("#apilist").hide(200);
        });



    });

    //js获取项目根路径，如： http://localhost:8083/uimcardprj
    function getRootPath() {
        //获取当前网址，如： http://localhost:8083/uimcardprj/share/meun.jsp
        var curWwwPath = window.document.location.href;
        //获取主机地址之后的目录，如： uimcardprj/share/meun.jsp
        var pathName = window.document.location.pathname;
        var pos = curWwwPath.indexOf(pathName);
        //获取主机地址，如： http://localhost:8083
        var localhostPaht = curWwwPath.substring(0, pos);
        //获取带"/"的项目名，如：/uimcardprj
        var projectName = pathName.substring(0, pathName.substr(1).indexOf('/') + 1);
        return (localhostPaht + projectName);
    }
</script>
</body>

</html>

ApiManagement/WebApplication1/Views/Shared/_Navigation.cshtml
<div class="clearfix">
    <aside class="sidebar">
        <nav class="sidebar-nav">
            <ul id="menu3">            
            </ul>
        </nav>
    </aside>
  
    <script>
        function getApiList() {
            var a=0;
            $.ajax({
                url: "@Url.Action("GetApiList", "ApiManagement")/", //请求的url地址http://localhost:7460/ApiManagement/GetApiList
                dataType: "json", //返回格式为json
                async: true,//请求是否异步，默认为异步，这也是ajax重要特性
              //  data: { "days": days, "starttime": starttime, "endtime": endtime },   //参数值
                type: "post", //请求方式
                beforeSend: function () {
                    //请求前的处理
                },
                success: function (data) {
                    var ulcontent="";
                    $(data).each(function () {
                        ulcontent += "<li><a href='/ApiManagement/Index?id=" + this["id"] + "&&sid=" + this["sid"] + "&&version=" + this["version"] + "'>" + this["api_name"] + "<span style='float:right;'>(version:" + this["version"] + ")</span><p>" + this["api_description"] + "</p></a></li>";
                    });
                    $("#menu3").empty();
                    $("#menu3").html(ulcontent);
                },
                complete: function () {

                    //请求完成的处理
                },
                error: function (data) {
                    console.log(data);
                    //请求出错处理
                }
            });


        }
        $(function() {
                getApiList();
                $('#menu3').metisMenu({
                    doubleTapToGo: true
                });
            });
    </script>
</div>